CREATE TABLE "startentrys" (
	"id"	INTEGER NOT NULL,
	"timestamp"	INTEGER NOT NULL,
	"title"	TEXT NOT NULL,
	"status"	INTEGER NOT NULL,
	"val1"	INTEGER NOT NULL,
	"val2"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);